<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('elements', function (Blueprint $table) {
            $table->id();
            $table->smallInteger('processor_id')->nullable()->default(NULL);
            $table->string('place-in-performance-rating')->nullable()->default(NULL);
            $table->string('market-segment')->nullable()->default(NULL);
            $table->string('architecture-codename')->nullable()->default(NULL);
            $table->string('release-date')->nullable()->default(NULL);
            $table->smallInteger('physical-cores')->nullable()->default(NULL);
            $table->smallInteger('threads')->nullable()->default(NULL);
            $table->smallInteger('base-clock-speed')->nullable()->default(NULL);
            $table->smallInteger('boost-clock-speed')->nullable()->default(NULL);
            $table->smallInteger('l1-cache')->nullable()->default(NULL);
            $table->smallInteger('l2-cache')->nullable()->default(NULL);
            $table->smallInteger('l3-cache')->nullable()->default(NULL);
            $table->smallInteger('chip-lithography')->nullable()->default(NULL);
            $table->string('die-size')->nullable()->default(NULL);
            $table->smallInteger('maximum-core-temperature')->nullable()->default(NULL);
            $table->integer('number-of-transistors')->nullable()->default(NULL);
            $table->smallInteger('64-bit-support')->nullable()->default(NULL);
            $table->smallInteger('number-of-cpus-in-a-configuration')->nullable()->default(NULL);
            $table->string('socket')->nullable()->default(NULL);
            $table->smallInteger('thermal-design-power-tdp')->nullable()->default(NULL);
            $table->smallInteger('aes-ni')->nullable()->default(NULL);
            $table->smallInteger('avx')->nullable()->default(NULL);
            $table->smallInteger('amd-v')->nullable()->default(NULL);
            $table->string('supported-memory-types')->nullable()->default(NULL);
            $table->smallInteger('integrated-graphics-card')->nullable()->default(NULL);
            $table->smallInteger('pcie-version')->nullable()->default(NULL);
            $table->smallInteger('value-for-money')->nullable()->default(NULL);
            $table->smallInteger('current-price')->nullable()->default(NULL);
            $table->smallInteger('maximum-case-temperature-tcase')->nullable()->default(NULL);
            $table->smallInteger('unlocked-multiplier')->nullable()->default(NULL);
            $table->string('instruction-set-extensions')->nullable()->default(NULL);
            $table->string('series')->nullable()->default(NULL);
            $table->smallInteger('speed-shift')->nullable()->default(NULL);
            $table->smallInteger('hyper-threading-technology')->nullable()->default(NULL);
            $table->smallInteger('thermal-monitoring')->nullable()->default(NULL);
            $table->smallInteger('flex-memory-access')->nullable()->default(NULL);
            $table->smallInteger('edb')->nullable()->default(NULL);
            $table->smallInteger('secure-key')->nullable()->default(NULL);
            $table->smallInteger('os-guard')->nullable()->default(NULL);
            $table->smallInteger('vt-d')->nullable()->default(NULL);
            $table->smallInteger('vt-x')->nullable()->default(NULL);
            $table->smallInteger('ept')->nullable()->default(NULL);
            $table->smallInteger('maximum-memory-size')->nullable()->default(NULL);
            $table->smallInteger('max-memory-channels')->nullable()->default(NULL);
            $table->smallInteger('ecc-memory-support')->nullable()->default(NULL);
            $table->smallInteger('quick-sync-video')->nullable()->default(NULL);
            $table->smallInteger('graphics-max-frequency')->nullable()->default(NULL);
            $table->smallInteger('execution-units')->nullable()->default(NULL);
            $table->smallInteger('number-of-displays-supported')->nullable()->default(NULL);
            $table->string('max-resolution-over-hdmi-14')->nullable()->default(NULL);
            $table->string('max-resolution-over-edp')->nullable()->default(NULL);
            $table->string('max-resolution-over-displayport')->nullable()->default(NULL);
            $table->smallInteger('directx')->nullable()->default(NULL);
            $table->smallInteger('opengl')->nullable()->default(NULL);
            $table->smallInteger('pci-express-lanes')->nullable()->default(NULL);
            $table->smallInteger('enhanced-speedstep-eist')->nullable()->default(NULL);
            $table->smallInteger('tsx')->nullable()->default(NULL);
            $table->smallInteger('txt')->nullable()->default(NULL);
            $table->smallInteger('maximum-memory-bandwidth')->nullable()->default(NULL);
            $table->smallInteger('sipp')->nullable()->default(NULL);
            $table->smallInteger('turbo-boost-max-30')->nullable()->default(NULL);
            $table->smallInteger('vpro')->nullable()->default(NULL);
            $table->smallInteger('windows-11-compatibility')->nullable()->default(NULL);
            $table->smallInteger('gpio')->nullable()->default(NULL);
            $table->smallInteger('4k-resolution-support')->nullable()->default(NULL);
            $table->smallInteger('usb-revision')->nullable()->default(NULL);
            $table->smallInteger('turbo-boost-technology')->nullable()->default(NULL);
            $table->smallInteger('idle-states')->nullable()->default(NULL);
            $table->smallInteger('clear-video-hd')->nullable()->default(NULL);
            $table->string('sgx')->nullable()->default(NULL);
            $table->smallInteger('launch-price-msrp')->nullable()->default(NULL);
            $table->smallInteger('place-by-popularity')->nullable()->default(NULL);
            $table->smallInteger('bus-support')->nullable()->default(NULL);
            $table->smallInteger('quickassist')->nullable()->default(NULL);
            $table->smallInteger('max-number-of-sata-6-gbs-ports')->nullable()->default(NULL);
            $table->smallInteger('number-of-usb-ports')->nullable()->default(NULL);
            $table->smallInteger('integrated-lan')->nullable()->default(NULL);
            $table->smallInteger('identity-protection')->nullable()->default(NULL);
            $table->smallInteger('max-video-memory')->nullable()->default(NULL);
            $table->smallInteger('clear-video')->nullable()->default(NULL);
            $table->smallInteger('intru-3d')->nullable()->default(NULL);
            $table->smallInteger('mpx')->nullable()->default(NULL);
            $table->smallInteger('smart-response')->nullable()->default(NULL);
            $table->smallInteger('edp')->nullable()->default(NULL);
            $table->smallInteger('displayport')->nullable()->default(NULL);
            $table->smallInteger('hdmi')->nullable()->default(NULL);
            $table->smallInteger('mipi-dsi')->nullable()->default(NULL);
            $table->smallInteger('dvi')->nullable()->default(NULL);
            $table->smallInteger('uart')->nullable()->default(NULL);
            $table->smallInteger('anti-theft')->nullable()->default(NULL);
            $table->smallInteger('total-number-of-sata-ports')->nullable()->default(NULL);
            $table->smallInteger('secure-boot')->nullable()->default(NULL);
            $table->smallInteger('my-wifi')->nullable()->default(NULL);
            $table->smallInteger('fma')->nullable()->default(NULL);
            $table->smallInteger('demand-based-switching')->nullable()->default(NULL);
            $table->smallInteger('pae')->nullable()->default(NULL);
            $table->smallInteger('edram')->nullable()->default(NULL);
            $table->smallInteger('vt-i')->nullable()->default(NULL);
            $table->smallInteger('smart-idle')->nullable()->default(NULL);
            $table->smallInteger('smart-connect')->nullable()->default(NULL);
            $table->smallInteger('hd-audio')->nullable()->default(NULL);
            $table->smallInteger('rst')->nullable()->default(NULL);
            $table->string('max-resolution-over-vga')->nullable()->default(NULL);
            $table->smallInteger('amt')->nullable()->default(NULL);
            $table->smallInteger('quiet-system')->nullable()->default(NULL);
            $table->smallInteger('powernow')->nullable()->default(NULL);
            $table->smallInteger('frtc')->nullable()->default(NULL);
            $table->smallInteger('freesync')->nullable()->default(NULL);
            $table->smallInteger('igpu-core-count')->nullable()->default(NULL);
            $table->smallInteger('switchable-graphics')->nullable()->default(NULL);
            $table->smallInteger('vulkan')->nullable()->default(NULL);
            $table->string('vid-voltage-range')->nullable()->default(NULL);
            $table->smallInteger('powertune')->nullable()->default(NULL);
            $table->smallInteger('trueaudio')->nullable()->default(NULL);
            $table->smallInteger('powergating')->nullable()->default(NULL);
            $table->smallInteger('virusprotect')->nullable()->default(NULL);
            $table->smallInteger('enduro')->nullable()->default(NULL);
            $table->smallInteger('uvd')->nullable()->default(NULL);
            $table->smallInteger('vce')->nullable()->default(NULL);
            $table->smallInteger('out-of-band-client-management')->nullable()->default(NULL);
            $table->smallInteger('raid')->nullable()->default(NULL);
            $table->smallInteger('iommu-20')->nullable()->default(NULL);
            $table->smallInteger('xfr')->nullable()->default(NULL);
            $table->smallInteger('sensemi')->nullable()->default(NULL);
            $table->smallInteger('monero-xmr-cryptonight')->nullable()->default(NULL);
            $table->smallInteger('bitcoin-btc-sha256')->nullable()->default(NULL);
            $table->smallInteger('instruction-replay')->nullable()->default(NULL);
            $table->smallInteger('dualgraphics')->nullable()->default(NULL);
            $table->smallInteger('fdi')->nullable()->default(NULL);
            $table->smallInteger('operating-temperature-range')->nullable()->default(NULL);
            $table->smallInteger('number-of-pipelines')->nullable()->default(NULL);
            $table->smallInteger('hsa')->nullable()->default(NULL);
            $table->smallInteger('fast-memory-access')->nullable()->default(NULL);
            $table->smallInteger('vga')->nullable()->default(NULL);
            $table->string('p0-vcore-voltage')->nullable()->default(NULL);
            $table->smallInteger('matrix-storage')->nullable()->default(NULL);
            $table->smallInteger('pci-support')->nullable()->default(NULL);
            $table->smallInteger('integrated-ide')->nullable()->default(NULL);
            $table->smallInteger('sdvo')->nullable()->default(NULL);
            $table->smallInteger('crt')->nullable()->default(NULL);
            $table->smallInteger('lvds')->nullable()->default(NULL);
            $table->smallInteger('quick-resume')->nullable()->default(NULL);
            $table->smallInteger('mipi')->nullable()->default(NULL);
            $table->smallInteger('io-acceleration')->nullable()->default(NULL);
            $table->smallInteger('fsb-parity')->nullable()->default(NULL);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('elements');
    }
};
